Repository elastic/apm-agent-java, pull requests merged in 2018-08, with the labels that each got.

#155 Update flag handling of TraceContext
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/TraceContext.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/transaction/TraceContextTest.java
Labels: [zube]: In Review

#157 Add getId method to public API
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/TransactionId.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/SpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/TransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#159 [0.6] Make header recording null safe (#158)
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/Request.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/report/serialize/DslJsonSerializerTest.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/ServletApiAdvice.java
Labels: backport

#161 JDBC integration testing with testcontainers
  apm-agent-plugins/apm-jdbc-plugin/pom.xml
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/jdbc/AbstractJdbcInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/jdbc/DataSourceIT.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/jdbc/JdbcDbIT.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/jdbc/JdbcInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/resources/container-license-acceptance.txt
  apm-agent-plugins/apm-jdbc-plugin/src/test/resources/testcontainers.properties
  integration-tests/simple-webapp-integration-test/pom.xml
  pom.xml
Labels: [zube]: In Review

#162 Don't call Throwable#getStackTrace in application threads
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/reporter/AbstractReporterBenchmark.java
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/reporter/HttpDslJsonReporterContinuousBenchmark.java
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/stacktrace/StackTraceFactoryBenchmark.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/ElasticApmTracerBuilder.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/ExceptionInfo.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/Log.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/stacktrace/Stacktrace.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/stacktrace/StacktraceFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/MockReporter.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/transaction/TransactionTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/serialize/DslJsonSerializerTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/StacktraceFactoryTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/StacktraceSerializationTest.java
  apm-agent-plugins/apm-apache-httpclient-plugin/pom.xml
  apm-agent-plugins/apm-apache-httpclient-plugin/src/test/java/co/elastic/apm/httpclient/ApacheHttpClientInstrumentationTest.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
Labels: [zube]: In Review

#172 Add span.tags
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/SizeOfSpan.java
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/reporter/AbstractReporterBenchmark.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/AbstractContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/SpanContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/TransactionContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/context/TransactionContextTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/SpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/opentracing/impl/ApmSpanInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/servlet/AsyncServletTest.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/web/BodyProcessor.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/web/SanitizingWebProcessor.java
  apm-agent-plugins/apm-web-plugin/src/test/java/co/elastic/apm/web/SanitizingWebProcessorTest.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#177 Add reference property file with all options to docs
  apm-agent-core/src/main/java/co/elastic/apm/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/logging/LoggingConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterConfiguration.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/web/WebConfiguration.java
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: [zube]: In Review

#184 Limit SQL statements to 10,000 chars
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/report/serialize/DslJsonSerializerTest.java
Labels: [zube]: Inbox
