Repository elastic/apm-agent-java, pull requests merged in 2018-11, with the labels that each got.

#270 Add FAQ section
  docs/faq.asciidoc
  docs/index.asciidoc
Labels: Docs, [zube]: In Review

#280 docs: fix spelling
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterConfiguration.java
  docs/configuration.asciidoc
Labels: Docs

#286 Adding Elasticsearch to Supported Technologies page
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#278 Add API methods to enable RUM trace correlation
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/SpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/TransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#281 Add annotations to create transactions and spans
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/CaptureSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/CaptureTransaction.java
  apm-agent-core/src/main/java/co/elastic/apm/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/bci/bytebuddy/AnnotationValueOffsetMappingFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/bci/bytebuddy/SimpleMethodSignatureOffsetMappingFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/stacktrace/StacktraceConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/AbstractInstrumentationTest.java
  apm-agent-core/src/test/resources/elasticapm.properties
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/ApiInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/ApiScopeInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/CaptureExceptionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/CaptureSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/CaptureTransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/ElasticApmApiInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/SpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/TransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/AnnotationApiTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/test/java/co/elastic/apm/es/restclient/v5_6/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/jaxrs/JaxRsTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/jdbc/AbstractJdbcInstrumentationTest.java
  docs/configuration.asciidoc
  docs/public-api.asciidoc
Labels: [zube]: In Review

#296 Server specific startup instructions
  docs/application-server-setup.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#297 docs: update links for v2
  docs/opentracing.asciidoc
Labels: Docs

#321 docs: fix static links 305
  docs/opentracing.asciidoc
Labels: Docs

#317 Reduce usages of guava map
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/jdbc/ConnectionInstrumentation.java
Labels: [zube]: In Review

#342 Changing documentation of min compile version from 1.6 to 1.5
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#336 Reversing order of system.hostname and system.platform
  apm-agent-core/src/main/java/co/elastic/apm/impl/payload/SystemInfo.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/payload/PayloadUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/payload/TransactionPayloadJsonSchemaTest.java
Labels: [zube]: In Review, type: bug

#343 Handling cases where APM server URL contains path
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
Labels: [zube]: In Review

#319 Use LiteBlockingWaitStrategy
  apm-agent-core/src/main/java/co/elastic/apm/report/ApmServerReporter.java
Labels: [zube]: In Review

#320 Omit instrumenting classes version pre Java 5
  CHANGELOG.md
  apm-agent-core/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/bci/bytebuddy/ErrorLoggingListener.java
  apm-agent-core/src/main/java/co/elastic/apm/bci/bytebuddy/MinimumClassFileVersionValidator.java
  apm-agent-core/src/test/java/co/elastic/apm/bci/InstrumentationTest.java
  docs/troubleshooting.asciidoc
Labels: [zube]: In Review

#350 Docs: Update agent introductions
  docs/intro.asciidoc
Labels: Docs

#316 Avoid setting request attributes to reduce allocations
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/AsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/FilterChainInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/servlet/ApmFilterTest.java
Labels: [zube]: In Review

#352 Update release process instructions
  CONTRIBUTING.md
Labels: [zube]: In Review
