Repository elastic/apm-agent-java, pull requests merged in 2018-12, with the labels that each got.

#358 Remove incubating label from Apache HttpClient instrumentation
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/httpclient/ApacheHttpClientInstrumentation.java
Labels: [zube]: In Review

#373 Fixing NOTE in docs
  apm-agent-core/src/main/java/co/elastic/apm/configuration/CoreConfiguration.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/web/WebConfiguration.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#375 docs: version cross doc links
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/opentracing.asciidoc
Labels: Docs

#340 to change apm.server_urls from localhost:8300 to localhost:8200
  docs/application-server-setup.asciidoc
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: [zube]: In Progress

#369 Adding to doc and examples
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/stacktrace/StacktraceConfiguration.java
  docs/application-server-setup.asciidoc
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: [zube]: In Review

#365 Set correct user-agent header for health check
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerHealthChecker.java
Labels: [zube]: In Review

#364 Remove module-info.java to not confuse early Tomcat 8.5 versions
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#363 Reduce log level for transformation errors caused by optional classes
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/ErrorLoggingListener.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/ConnectionInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/PreparedStatementInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
Labels: [zube]: In Review

#380 Cach all exceptions in advices
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/InstrumentationTest.java
  apm-agent-plugins/README.md
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpClientInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/ApiScopeInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureExceptionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureTransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/ElasticApmApiInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/SpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/ConnectionInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/PreparedStatementInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmScopeInstrumentation.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanBuilderInstrumentation.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanInstrumentation.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ScopeManagerInstrumentation.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/SpanContextInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-spring-resttemplate-plugin/src/main/java/co/elastic/apm/agent/resttemplate/SpringRestTemplateInstrumentation.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/SpringTransactionNameInstrumentation.java
Labels: [zube]: In Review

#314 [APM-CI] Java agent Pipeline version 0
  .gitignore
  Jenkinsfile
  pom.xml
  scripts/jenkins/docs.sh
  scripts/jenkins/run-benchmarks.sh
  scripts/jenkins/smoketests-01.sh
  scripts/jenkins/smoketests-02.sh
Labels: [zube]: In Progress, automation

#306 Add capture_headers option
  apm-agent-benchmarks/src/main/java/co/elastic/apm/agent/benchmark/ElasticApmContinuousBenchmark.java
  apm-agent-benchmarks/src/main/java/co/elastic/apm/agent/benchmark/MockHttpServletRequest.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/Request.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/Response.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/helper/ApmAsyncListener.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ApmFilterTest.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/agent/web/WebConfiguration.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#294 Make public API setters fluent
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/AbstractSpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/AbstractSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/LegacySpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/SpanInstrumentationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#385 Async Servlet state management changes
  apm-agent-api/src/main/java/co/elastic/apm/api/AbstractSpanImpl.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/helper/ApmAsyncListener.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/helper/StartAsyncAdviceHelperImpl.java
Labels: [zube]: In Review

#368 Finding and sending container ID
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/SystemInfo.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/ContainerInfoTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  integration-tests/simple-webapp-integration-test/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
Labels: [zube]: In Review
