Repository elastic/apm-agent-java, pull requests merged in 2018-09, with the labels that each got.

#181 Implement exponential backoff for intake v2
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
Labels: [zube]: In Review, component: reporter

#188 Align configuration options with other agents
  .gitignore
  apm-agent-core/src/main/java/co/elastic/apm/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/configuration/StartupInfo.java
  apm-agent-core/src/main/java/co/elastic/apm/logging/LoggingConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/configuration/StartupInfoTest.java
  apm-agent-core/src/test/java/co/elastic/apm/logging/LoggingConfigurationTest.java
  apm-agent-core/src/test/resources/elasticapm.properties
  docs/configuration.asciidoc
  docs/troubleshooting.asciidoc
Labels: [zube]: In Review

#189 Support duration units in config options
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/configuration/StartupInfo.java
  apm-agent-core/src/main/java/co/elastic/apm/configuration/converter/TimeDuration.java
  apm-agent-core/src/main/java/co/elastic/apm/configuration/converter/TimeDurationValueConverter.java
  apm-agent-core/src/main/java/co/elastic/apm/configuration/converter/package-info.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/stacktrace/StacktraceConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV1ReportingEventHandler.java
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterFactory.java
  apm-agent-core/src/test/java/co/elastic/apm/configuration/StartupInfoTest.java
  apm-agent-core/src/test/java/co/elastic/apm/configuration/converter/TimeDurationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/configuration/converter/TimeDurationValueConverterTest.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ApmServerReporterTest.java
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: [zube]: In Review

#190 Client-side load balancing
  CHANGELOG.md
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/reporter/AbstractHttpReporterBenchmark.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ApmServerHealthChecker.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ApmServerHttpPayloadSender.java
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ReporterFactoryTest.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  pom.xml
Labels: [zube]: In Review

#193 Implement byte unit for api_request_size config
  apm-agent-core/src/main/java/co/elastic/apm/configuration/converter/ByteValue.java
  apm-agent-core/src/main/java/co/elastic/apm/configuration/converter/ByteValueConverter.java
  apm-agent-core/src/main/java/co/elastic/apm/report/ReporterConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/configuration/converter/ByteValueTest.java
Labels: [zube]: In Progress

#203 Enable complex wildcard patterns
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/matcher/WildcardMatcher.java
  apm-agent-core/src/test/java/co/elastic/apm/matcher/WildcardMatcherTest.java
  apm-agent-core/src/test/resources/elasticapm.properties
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/web/WebConfiguration.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#201 Use updated /intake/v2/events url
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
Labels: [zube]: In Review

#204 Move tags element to be nested under Context rather than Db
  .gitignore
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/AbstractContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/SpanContext.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/payload/TransactionPayloadJsonSchemaTest.java
Labels: [zube]: In Review, type: bug

#206 Add support for error.culprit
  apm-agent-benchmarks/src/main/java/co/elastic/apm/benchmark/SizeOfSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/MockTracer.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/ApmServerReporterTest.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/ErrorCaptureTest.java
  apm-agent-plugins/apm-web-plugin/src/test/java/co/elastic/apm/web/BodyProcessorTest.java
  apm-agent-plugins/apm-web-plugin/src/test/java/co/elastic/apm/web/SanitizingWebProcessorTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#207 Unnest exception types matching *Nested*Exception by default
  apm-agent-core/src/main/java/co/elastic/apm/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/MockTracer.java
  apm-agent-core/src/test/java/org/example/stacktrace/ErrorCaptureTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/StacktraceSerializationTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#216 Proper handling of invalid traceparent header
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/SpanId.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/TraceId.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/util/HexUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/transaction/TraceContextTest.java
  apm-agent-core/src/test/java/co/elastic/apm/util/HexUtilsTest.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
Labels: [zube]: In Review

#210 Add random jitter to backoff period
  apm-agent-core/src/main/java/co/elastic/apm/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/test/java/co/elastic/apm/report/IntakeV2ReportingEventHandlerTest.java
Labels: [zube]: In Review

#217 Error id adjustments for intake v2
  apm-agent-core/src/main/java/co/elastic/apm/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/sampling/ConstantSampler.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/sampling/ProbabilitySampler.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/sampling/Sampler.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Id.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/SpanId.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/TraceId.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/sampling/ProbabilitySamplerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/transaction/IdTest.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/transaction/TraceContextTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/plugin/api/SpanInstrumentation.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
Labels: [zube]: In Review

#218 Add http url to span context
  apm-agent-core/src/main/java/co/elastic/apm/impl/context/SpanContext.java
  apm-agent-core/src/main/java/co/elastic/apm/impl/transaction/Http.java
  apm-agent-core/src/main/java/co/elastic/apm/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/httpclient/ApacheHttpClientInstrumentation.java
  apm-agent-plugins/apm-httpclient-core/src/main/java/co/elastic/apm/http/client/HttpClientHelper.java
  apm-agent-plugins/apm-httpclient-core/src/test/java/co/elastic/apm/httpclient/AbstractHttpClientInstrumentationTest.java
  apm-agent-plugins/apm-spring-resttemplate-plugin/src/main/java/co/elastic/apm/resttemplate/SpringRestTemplateInstrumentation.java
Labels: [zube]: In Review
