Repository elastic/apm-agent-java, pull requests merged in 2019-10, with the labels that each got.

#872 Add service.node.configured_name
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/Node.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/Service.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/ServiceFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  docs/configuration.asciidoc
  docs/metrics.asciidoc
Labels: [zube]: In Review

#873 Configurable ignored exceptions
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/matcher/WildcardMatcher.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/SpyConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#880 ci(jenkins): reuse agents (2 less agents to be used)
  Jenkinsfile
Labels: automation

#878 Report exception cause to backend
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/error/ErrorPayload.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/Payload.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/TransactionPayload.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/PayloadSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/MockReporter.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/PayloadUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
Labels: [zube]: In Review

#874 Tracing not-excluded URLs
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
Labels: [zube]: In Review

#816 JMS changing polling logic
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-plugins/apm-jms-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/BaseJmsInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelper.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelperImpl.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageListenerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/MessagingConfiguration.java
  apm-agent-plugins/apm-jms-plugin/src/main/resources/META-INF/services/org.stagemonitor.configuration.ConfigurationOptionProvider
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqArtemisFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/JmsInstrumentationIT.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/spring/SpringJmsTest.java
Labels: [zube]: In Review

#898 Add method monitoring overview to supported technologies
  docs/supported-technologies.asciidoc
Labels: Docs

#883 Report affected rows for DML statements
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Db.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/DataSourceIT.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/JdbcDbIT.java
Labels: [zube]: In Review

#905 Add @Traced annotation
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/Traced.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/TracedInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/AnnotationApiTest.java
  docs/public-api.asciidoc
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review
