Repository elastic/apm-agent-java, pull requests merged in 2019-05, with the labels that each got.

#619 Add a step to build to create a dependency list
  Jenkinsfile
  apm-agent-core/pom.xml
Labels: [zube]: In Review

#573 [APM-CI][Java] use local weblogic Docker image cached
  Jenkinsfile
Labels: automation

#624 Mark some reporter configurations as dynamic
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterConfiguration.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#587 Recycle via reference counting
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeBaseWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeCallableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeRunnableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/error/ErrorPayload.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/Payload.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/TransactionPayload.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerReporter.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/MockReporter.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ScopeManagementTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/ExecutorServiceDoubleWrappingTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/FailingExecutorInstrumentationTest.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/OkHttp3ClientAsyncInstrumentation.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/OkHttpClientAsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
Labels: [zube]: In Review

#616 Fix intake v2 trace logging
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
Labels: [zube]: In Review

#625 Add support for AsyncHttpClient
  CHANGELOG.md
  apm-agent-plugins/apm-asynchttpclient-plugin/pom.xml
  apm-agent-plugins/apm-asynchttpclient-plugin/src/main/java/co/elastic/apm/agent/asynchttpclient/AbstractAsyncHttpClientInstrumentation.java
  apm-agent-plugins/apm-asynchttpclient-plugin/src/main/java/co/elastic/apm/agent/asynchttpclient/package-info.java
  apm-agent-plugins/apm-asynchttpclient-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-asynchttpclient-plugin/src/test/java/co/elastic/apm/agent/asynchttpclient/AsyncHttpClientInstrumentationTest.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#627 [APM-CI][All] Make the trigger by comment case-insensitive
  Jenkinsfile
Labels: automation

#621 Adding NOTICE and LICENSE
  LICENSE
  NOTICE
  apm-agent-api/pom.xml
  apm-agent-api/src/main/resources/META-INF/NOTICE
  apm-agent-attach/pom.xml
  apm-agent-attach/resources/NOTICE
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/main/resources/META-INF/NOTICE
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-plugins/apm-servlet-plugin/src/main/resources/META-INF/NOTICE
  apm-agent-plugins/apm-web-plugin/src/main/resources/META-INF/NOTICE
  apm-opentracing/pom.xml
  apm-opentracing/src/main/resources/META-INF/NOTICE
  elastic-apm-agent/pom.xml
  elastic-apm-agent/src/main/resources/META-INF/NOTICE
  license/licenses.properties
  licenses/apache2_license/apache2-license-header.txt
  licenses/licenses.properties
  pom.xml
  scripts/jenkins/smoketests-01.sh
Labels: [zube]: In Review

#606 Add support for custom context
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/TransactionContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/context/TransactionContextTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#626 Excluding Pilotfish NTMThreadPool from Executor instr and fix NPE
  CHANGELOG.md
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletTransactionHelperTest.java
Labels: [zube]: In Review, type: bug

#629 Calculate free memory based on /proc/meminfo on Linux
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/SystemMetrics.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-core/src/test/resources/proc/meminfo
  apm-agent-core/src/test/resources/proc/meminfo-3.14
Labels: [zube]: In Review

#632 Sanitize URLs of HTTP client spans
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Http.java
  apm-agent-plugins/apm-httpclient-core/src/test/java/co/elastic/apm/agent/httpclient/AbstractHttpClientInstrumentationTest.java
Labels: [zube]: In Review

#637 Adding ephemeral_id field
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/Agent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
Labels: [zube]: In Review

#641 Adding a configuration option for bootdelegation packages
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/OsgiBootDelegationEnabler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/InstrumentationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/OsgiBootDelegationEnablerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterIntegrationTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#543 Add support for global labels
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/MetaData.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT_RealReporter.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#646 Cache AttachmentProvider
  apm-agent-attach/src/main/java/co/elastic/apm/attach/CachedAttachmentProvider.java
  apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java
  apm-agent-attach/src/main/java/co/elastic/apm/attach/RemoteAttacher.java
Labels: [zube]: In Review

#623 [ci] add files for JJBB jobs
  .ci/bin/check_paths_for_matches.py
  .ci/jobs/apm-agent-java-mbp.yml
  .ci/jobs/apm-agent-java.yml
  .ci/jobs/defaults.yml
Labels: [zube]: In Review
