Repository elastic/apm-agent-java, pull requests merged in 2019-03, with the labels that each got.

#508 [APM-CI] Store artifacts in Jenkins
  Jenkinsfile
Labels: automation

#501 Fix metrics NaN issue
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/MetricRegistrySerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/MetricSetSerializationTest.java
Labels: [zube]: In Review, type: bug

#497 Add support for Number and boolean tags
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/AbstractSpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/AbstractContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/TransactionContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Id.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/MetricSet.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/MetricRegistrySerializer.java
  apm-agent-core/src/main/resources/schema/context.json
  apm-agent-core/src/test/java/co/elastic/apm/agent/MockReporter.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/context/TransactionContextTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/AbstractSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/LegacySpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/SpanInstrumentationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/AnnotationApiTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/test/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanInstrumentation.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
  docs/configuration.asciidoc
  docs/metrics.asciidoc
  docs/public-api.asciidoc
Labels: [zube]: In Review

#509 Executors instrumentation - select wrapper based on span lifecycle
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/ContextInScopeCallableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/ContextInScopeRunnableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeCallableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeRunnableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ScopeManagementTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/FailingExecutorInstrumentationTest.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/AsyncServletTest.java
  apm-agent-plugins/apm-urlconnection-plugin/src/test/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentationTest.java
Labels: [zube]: In Review, type: enhancement

#500 Fix logging integration
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ActivationListener.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-plugins/apm-slf4j-plugin/src/main/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListener.java
  apm-agent-plugins/apm-slf4j-plugin/src/test/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListenerTest.java
Labels: [zube]: In Review, type: bug

#518 [APM-CI] archive apm-agent-attach-*.jar files
  Jenkinsfile
Labels: automation

#524 Create cloudfoundry index.yml
  cloudfoundry/index.yml
Labels: [zube]: In Review

#515 Elasticsearch client async instr
  CHANGELOG.md
  apm-agent-benchmarks/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/HelperClassManager.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientSyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/test/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchClientSyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ElasticsearchRestClientInstrumentationHelper.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ElasticsearchRestClientInstrumentationHelperImpl.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ResponseListenerWrapper.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/package-info.java
  apm-agent-plugins/apm-es-restclient-plugin/pom.xml
  docs/supported-technologies.asciidoc
  pom.xml
Labels: [zube]: In Review

#528 [APM-CI] use current as pipeline shared library version
  Jenkinsfile
  scripts/jenkins/docs.sh
Labels: automation

#529 Add more comprehensive inject/extract example to API docs
  apm-agent-api/src/main/java/co/elastic/apm/api/ElasticApm.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  docs/public-api.asciidoc
Labels: [zube]: Inbox

#527 Add config option reference
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/java/co/elastic/apm/agent/configuration/ConfigurationExporterTest.java
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: [zube]: Inbox

#530 Override span.id instead of removing and adding
  apm-agent-plugins/apm-slf4j-plugin/src/main/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListener.java
Labels: [zube]: In Review

#536 Don't instrument Hazelcast Executors
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
Labels: [zube]: In Review

#531 Fixed Nullpointer in maven-shade.plugin by upgrading to 3.2.1
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#540 Document when options and APIs were added
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/stacktrace/StacktraceConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterConfiguration.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsConfiguration.java
  docs/configuration.asciidoc
  docs/public-api.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: [zube]: In Review

#542 Align default transaction name to '<method> unknown route'
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
Labels: [zube]: In Review

#541 Allow setting manual start and end timestamps
  CHANGELOG.md
  apm-agent-api/src/main/java/co/elastic/apm/api/AbstractSpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/AbstractSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#514 Use display-name or context path as the default service name
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/methodmatching/TraceMethodInstrumentation.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/ServiceNameUtil.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/AbstractInstrumentationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/SpyConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ScopeManagementTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/StacktraceSerializationTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureExceptionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureTransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/ElasticApmApiInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/test/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT_RealReporter.java
  apm-agent-plugins/apm-httpclient-core/src/test/java/co/elastic/apm/agent/httpclient/AbstractHttpClientInstrumentationTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentationTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/ExecutorServiceInstrumentationTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/FailingExecutorInstrumentationTest.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-jaxws-plugin/src/test/java/co/elastic/apm/agent/jaxws/JaxWsTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanBuilderInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletContextServiceNameInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletInstrumentationTest.java
  apm-agent-plugins/apm-slf4j-plugin/src/test/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListenerTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/SpringServiceNameInstrumentation.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/JsfApplicationServerTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/JsfServletContainerTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/ServletApiTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/SoapTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/TestApp.java
  integration-tests/spring-boot-2/spring-boot-2-base/src/test/java/co/elastic/apm/spring/boot/AbstractSpringBootTest.java
  integration-tests/spring-boot-2/spring-boot-2-base/src/test/resources/application.properties
Labels: [zube]: In Progress

#498 Capture text-based request bodies
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/Request.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/TransactionContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Db.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/matcher/WildcardMatcher.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/RequestStreamRecordingInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/helper/InputStreamFactoryHelperImpl.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/helper/RecordingServletInputStreamWrapper.java
  apm-agent-plugins/apm-servlet-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ApmFilterTest.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/TestRequestBodyCapturing.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/agent/web/WebConfiguration.java
  docs/configuration.asciidoc
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/JettyIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/WebSphereIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/JsfApplicationServerTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/ServletApiTestApp.java
  integration-tests/simple-webapp/src/main/java/co/elastic/webapp/EchoServlet.java
  integration-tests/simple-webapp/src/main/webapp/WEB-INF/web.xml
Labels: [zube]: In Review

#526 Support async OkHttp calls
  CHANGELOG.md
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/OkHttp3ClientAsyncInstrumentation.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/OkHttpClientAsyncInstrumentation.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/WrapperCreator.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-okhttp-plugin/src/test/java/co/elastic/apm/agent/okhttp/OkHttp3ClientAsyncInstrumentationTest.java
  apm-agent-plugins/apm-okhttp-plugin/src/test/java/co/elastic/apm/agent/okhttp/OkHttpClientAsyncInstrumentationTest.java
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#545 Update Byte Buddy to 1.9.11
  pom.xml
Labels: [zube]: In Review

#544 Add support for providing config on attach
  apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java
  apm-agent-attach/src/main/java/co/elastic/apm/attach/RemoteAttacher.java
  apm-agent-attach/src/test/java/co/elastic/apm/attach/RemoteAttacherTest.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/AgentArgumentsConfigurationSource.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/AgentArgumentsConfigurationSourceTest.java
Labels: [zube]: In Review
