Repository elastic/apm-agent-java, pull requests merged in 2019-06, with the labels that each got.

#649 Fix service loading for WebLogic 12.2.1.2.0
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/util/DependencyInjectingServiceLoader.java
Labels: [zube]: In Review

#651 Allow log_file to be a relative path
  apm-agent-core/src/main/java/co/elastic/apm/agent/logging/LoggingConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/logging/LoggingConfigurationTest.java
Labels: [zube]: In Review

#650 Basic JMS Support
  CHANGELOG.md
  apm-agent-plugins/apm-httpclient-core/pom.xml
  apm-agent-plugins/apm-java-concurrent-plugin/pom.xml
  apm-agent-plugins/apm-jaxws-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/BaseJmsInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelper.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelperImpl.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageListenerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageProducerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/package-info.java
  apm-agent-plugins/apm-jms-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqArtemisFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/BrokerFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/JmsInstrumentationIT.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#653 Disable metrics when active=false
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerReporter.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterFactory.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT_RealReporter.java
Labels: [zube]: In Review

#661 add tip on wrong jar file usage
  docs/troubleshooting.asciidoc
Labels: Docs, component: documentation, type: enhancement

#659 Removing abs_path and adding module to serialized stack frames
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/StacktraceSerializationTest.java
Labels: [zube]: In Review

#662 Handling recycling race and volatile read-writes in Apache Async client
  CHANGELOG.md
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/HttpAsyncRequestProducerWrapper.java
Labels: [zube]: In Review, type: bug

#665 Fix version discovery for URL-encoded jars
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
Labels: type: bug

#668 feat(jenkins): GH Checks for the PR
  Jenkinsfile
Labels: automation

#675 Fix error serialization
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
Labels: type: bug

#683 Implementation version- parsing dashes and reducing log level
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchersTest.java
Labels: [zube]: In Review

#677 ci(jenkins): trigger async ITs and update github check for the pull requests
  Jenkinsfile
Labels: automation

#678 Jms receiveNoWait test
  apm-agent-plugins/apm-jms-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/JmsInstrumentationIT.java
Labels: [zube]: In Review

#688 Enabling build on Windows
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/SystemInfo.java
  pom.xml
Labels: [zube]: In Review

#655 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#697 ci(jenkins): notify first time contributor github check
  Jenkinsfile
Labels: automation
