Repository elastic/apm-agent-java, pull requests merged in 2019-07, with the labels that each got.

#620 Use @javax.ws.rs.Path value as transaction name
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureTransactionInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/pom.xml
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsConfiguration.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsOffsetMappingFactory.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-jaxws-plugin/src/main/java/co/elastic/apm/agent/jaxws/JaxWsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-scheduled-annotation-plugin/src/main/java/co/elastic/apm/agent/spring/scheduled/ScheduledTransactionNameInstrumentation.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#699 Giving examples for dynamic config options in docs
  docs/configuration.asciidoc
Labels: [zube]: In Review

#692 689 instrument quartz jobs
  apm-agent-plugins/apm-quartz-job-plugin/pom.xml
  apm-agent-plugins/apm-quartz-job-plugin/src/main/java/co/elastic/apm/agent/quartz/job/JobTransactionNameAdvice.java
  apm-agent-plugins/apm-quartz-job-plugin/src/main/java/co/elastic/apm/agent/quartz/job/JobTransactionNameInstrumentation.java
  apm-agent-plugins/apm-quartz-job-plugin/src/main/java/co/elastic/apm/agent/quartz/job/package-info.java
  apm-agent-plugins/apm-quartz-job-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-quartz-job-plugin/src/test/java/co/elastic/apm/agent/quartz/job/JobTransactionNameInstrumentationTest.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#704 Do not let Reporter Timer thread die
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
Labels: [zube]: In Review, type: bug

#718 Attempting System CL when Context CL is null and caching loading failure
  apm-agent-plugins/apm-slf4j-plugin/src/main/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListener.java
  apm-agent-plugins/apm-slf4j-plugin/src/test/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListenerTest.java
Labels: [zube]: In Review

#684 Fix rendering of bootdelegation examples
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#706 Adding debug logging for reason not capturing request body
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
Labels: [zube]: In Review

#695 Parsing container ID in cloud foundry garden
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/SystemInfo.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/ContainerInfoTest.java
Labels: [zube]: In Review, type: bug

#694 Logging debug info regarding Spring MVC transaction name setting
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/SpringTransactionNameInstrumentation.java
Labels: [zube]: In Review

#714 Supporting SpringMapMessageListener
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/TraceContextTest.java
  apm-agent-plugins/apm-jms-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageListenerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageProducerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/spring/SpringJmsTest.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/spring/SpringMapMessageListener.java
  apm-agent-plugins/apm-jms-plugin/src/test/resources/app-context.xml
Labels: [zube]: In Review

#640 Remote config
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/ApmServerConfigurationSource.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/MetaData.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerHealthChecker.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/PayloadSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/ApmServerConfigurationSourceTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ReporterFactoryTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT_RealReporter.java
  pom.xml
Labels: [zube]: In Review

#588 Timing breakdown
  NOTICE
  apm-agent-benchmarks/src/main/java/co/elastic/apm/agent/benchmark/ElasticApmContinuousBenchmark.java
  apm-agent-core/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeCallableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeRunnableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/Labels.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/MetricRegistry.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/MetricSet.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/Timer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/JvmGcMetrics.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/JvmMemoryMetrics.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/SystemMetrics.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/ThreadMetrics.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/MetricRegistrySerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/util/KeyListConcurrentHashMap.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/MockTracer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/SpyConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ScopeManagementTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/SpanTypeBreakdownTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/PayloadUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/SpanTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/TransactionTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/LabelsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/MetricRegistryTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/JvmMemoryMetricsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/ThreadMetricsTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ReporterFactoryTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/MetricSetSerializationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/ElasticApmApiInstrumentationTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-web-plugin/src/test/java/co/elastic/apm/agent/web/SanitizingWebProcessorTest.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
  docs/configuration.asciidoc
  docs/metrics.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#735 Add database link to span context(#732)
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Db.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/resources/schema/transactions/span.json
  apm-agent-core/src/test/java/co/elastic/apm/agent/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
Labels: [zube]: In Review

#734 make server_urls dynamically reloadable
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#738 Fixing TraceContext recycling and making OpenTracing replaceable span volatile
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-opentracing/src/main/java/co/elastic/apm/opentracing/ApmSpan.java
Labels: [zube]: In Review

#744 Try to stabilize test
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
Labels: [zube]: In Review

#745 ci: remove the documentation stage
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#746 Drop non-string labels if connected to older APM Server
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerHealthChecker.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterFactory.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/util/Version.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/MockReporter.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/ApmServerConfigurationSourceTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/TransactionTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerReporterIntegrationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandlerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-core/src/test/java/org/example/stacktrace/StacktraceSerializationTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT_RealReporter.java
Labels: [zube]: In Review

#743 Add dedicated feature flag for breakdown_metrics
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/SpanTypeBreakdownTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#739 Add feature flag for remote config
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/ApmServerConfigurationSource.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/configuration/ApmServerConfigurationSourceTest.java
Labels: [zube]: In Review

#742 Make log correlation GA
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ActivationListener.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/logging/LoggingConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/TransactionPayloadJsonSchemaTest.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanBuilderInstrumentation.java
  apm-agent-plugins/apm-slf4j-plugin/src/main/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListener.java
  apm-agent-plugins/apm-slf4j-plugin/src/test/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListenerTest.java
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#750 Add config_file option
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/logging/LoggingConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilderTest.java
  docs/configuration.asciidoc
  pom.xml
Labels: [zube]: In Review

#748 Introduce priorities for transaction name
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/TransactionUtils.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/methodmatching/TraceMethodInstrumentationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/SpanTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/SystemMetricsTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/AbstractSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureTransactionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/LegacySpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/SpanInstrumentationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/AnnotationApiTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/test/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/AbstractEs6_4ClientInstrumentationTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/test/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchRestClientInstrumentationIT_RealReporter.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/test/java/co/elastic/apm/agent/es/restclient/AbstractEsClientInstrumentationTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/ExecutorServiceDoubleWrappingTest.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-jaxws-plugin/src/main/java/co/elastic/apm/agent/jaxws/JaxWsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jaxws-plugin/src/test/java/co/elastic/apm/agent/jaxws/JaxWsTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelperImpl.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/JmsInstrumentationIT.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/spring/SpringJmsTest.java
  apm-agent-plugins/apm-jsf-plugin/src/main/java/co/elastic/apm/agent/jsf/JsfLifecycleInstrumentation.java
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanInstrumentation.java
  apm-agent-plugins/apm-quartz-job-plugin/src/test/java/co/elastic/apm/agent/quartz/job/JobTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-scheduled-annotation-plugin/src/test/java/co/elastic/apm/agent/spring/scheduled/ScheduledTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ApmFilterTest.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/AsyncServletTest.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletTransactionHelperTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/SpringTransactionNameInstrumentation.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/ApmHandlerInterceptorTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/DispatcherServletRenderInstrumentationTest.java
  apm-opentracing/src/test/java/co/elastic/apm/opentracing/OpenTracingBridgeTest.java
  integration-tests/spring-boot-1-5/src/test/java/co/elastic/apm/spring/boot/SpringBoot1_5IT.java
  integration-tests/spring-boot-2/spring-boot-2-base/src/test/java/co/elastic/apm/spring/boot/AbstractSpringBootTest.java
Labels: [zube]: In Review

#751 Use JSP path name as transaction name
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
Labels: [zube]: In Review, state: blocked

#754 Add example for context delegation through BlockingQueue using API
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/BlockingQueueContextPropagationTest.java
Labels: [zube]: In Review
