Repository elastic/apm-agent-java, pull requests merged in 2019-11, with the labels that each got.

#896 Add checkbox for excluding non-supported versions
  .github/pull_request_template.md
Labels: [zube]: In Review

#927 Refactor plugin versions & cleanup pom.xml
  apm-agent-api/pom.xml
  apm-agent-attach/pom.xml
  apm-agent-benchmarks/pom.xml
  apm-agent-core/pom.xml
  apm-agent-plugins/apm-apache-httpclient-plugin/pom.xml
  apm-agent-plugins/apm-api-plugin/pom.xml
  apm-agent-plugins/apm-asynchttpclient-plugin/pom.xml
  apm-agent-plugins/apm-error-logging-plugin/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-7_1/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/pom.xml
  apm-agent-plugins/apm-es-restclient-plugin/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-common/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/pom.xml
  apm-agent-plugins/apm-httpclient-core/pom.xml
  apm-agent-plugins/apm-java-concurrent-plugin/pom.xml
  apm-agent-plugins/apm-jaxrs-plugin/pom.xml
  apm-agent-plugins/apm-jaxws-plugin/pom.xml
  apm-agent-plugins/apm-jdbc-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/pom.xml
  apm-agent-plugins/apm-jmx-plugin/pom.xml
  apm-agent-plugins/apm-jsf-plugin/pom.xml
  apm-agent-plugins/apm-mule4-plugin/pom.xml
  apm-agent-plugins/apm-okhttp-plugin/pom.xml
  apm-agent-plugins/apm-opentracing-plugin/pom.xml
  apm-agent-plugins/apm-quartz-job-plugin/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-jedis-2-tests/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-jedis-3-tests/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-redis-common/pom.xml
  apm-agent-plugins/apm-redis-plugin/pom.xml
  apm-agent-plugins/apm-scheduled-annotation-plugin/pom.xml
  apm-agent-plugins/apm-servlet-plugin/pom.xml
  apm-agent-plugins/apm-slf4j-plugin/pom.xml
  apm-agent-plugins/apm-spring-resttemplate-plugin/pom.xml
  apm-agent-plugins/apm-spring-webmvc-plugin/pom.xml
  apm-agent-plugins/apm-urlconnection-plugin/pom.xml
  apm-agent-plugins/apm-web-plugin/pom.xml
  apm-agent-plugins/pom.xml
  apm-opentracing/pom.xml
  elastic-apm-agent/pom.xml
  integration-tests/application-server-integration-tests/pom.xml
  integration-tests/jsf-app/jsf-app-standalone/pom.xml
  integration-tests/jsf-app/pom.xml
  integration-tests/pom.xml
  integration-tests/simple-webapp/pom.xml
  integration-tests/soap-test/pom.xml
  integration-tests/spring-boot-1-5/pom.xml
  integration-tests/spring-boot-2/pom.xml
  integration-tests/spring-boot-2/spring-boot-2-base/pom.xml
  integration-tests/spring-boot-2/spring-boot-2-jetty/pom.xml
  integration-tests/spring-boot-2/spring-boot-2-tomcat/pom.xml
  integration-tests/spring-boot-2/spring-boot-2-undertow/pom.xml
  pom.xml
Labels: [zube]: In Review, technical debt

#835 MongoDB sync client instrumentation
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmInstrumentation.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/TestClassWithDependencyRunner.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientSyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ElasticsearchRestClientInstrumentationHelperImpl.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ResponseListenerWrapper.java
  apm-agent-plugins/apm-mongoclient-plugin/pom.xml
  apm-agent-plugins/apm-mongoclient-plugin/src/main/java/co/elastic/apm/agent/mongoclient/ConnectionAdvice.java
  apm-agent-plugins/apm-mongoclient-plugin/src/main/java/co/elastic/apm/agent/mongoclient/ConnectionCommandInstrumentation.java
  apm-agent-plugins/apm-mongoclient-plugin/src/main/java/co/elastic/apm/agent/mongoclient/ConnectionInstrumentation.java
  apm-agent-plugins/apm-mongoclient-plugin/src/main/java/co/elastic/apm/agent/mongoclient/MongoClientInstrumentation.java
  apm-agent-plugins/apm-mongoclient-plugin/src/main/java/co/elastic/apm/agent/mongoclient/package-info.java
  apm-agent-plugins/apm-mongoclient-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-mongoclient-plugin/src/test/java/co/elastic/apm/agent/mongoclient/AbstractMongoClientInstrumentationTest.java
  apm-agent-plugins/apm-mongoclient-plugin/src/test/java/co/elastic/apm/agent/mongoclient/MongoClientAsyncInstrumentationIT.java
  apm-agent-plugins/apm-mongoclient-plugin/src/test/java/co/elastic/apm/agent/mongoclient/MongoClientSyncInstrumentationIT.java
  apm-agent-plugins/apm-mongoclient-plugin/src/test/java/co/elastic/apm/agent/mongoclient/MongoClientSyncVersionIT.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
  pom.xml
Labels: [zube]: In Review

#936 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#911 JMS - some more enhancements
  CHANGELOG.md
  apm-agent-benchmarks/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/AbstractContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/BodyProcessor.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/Message.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/Request.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/SanitizingWebProcessor.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/web/ResultUtil.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/web/WebConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/util/NoRandomAccessMap.java
  apm-agent-core/src/main/resources/META-INF/services/co.elastic.apm.agent.report.processor.Processor
  apm-agent-core/src/main/resources/META-INF/services/org.stagemonitor.configuration.ConfigurationOptionProvider
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/context/BodyProcessorTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/context/SanitizingWebProcessorTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/context/web/ResultUtilTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/util/NoRandomAccessMapTest.java
  apm-agent-plugins/apm-jaxrs-plugin/pom.xml
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelper.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelperImpl.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageListenerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/MessagingConfiguration.java
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/package-info.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqArtemisFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/ActiveMqFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/BrokerFacade.java
  apm-agent-plugins/apm-jms-plugin/src/test/java/co/elastic/apm/agent/jms/JmsInstrumentationIT.java
  apm-agent-plugins/apm-opentracing-plugin/pom.xml
  apm-agent-plugins/apm-opentracing-plugin/src/main/java/co/elastic/apm/agent/opentracing/impl/ApmSpanInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/pom.xml
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ApmFilterTest.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletInstrumentationTest.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletTransactionHelperTest.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/TestRequestBodyCapturing.java
  apm-agent-plugins/apm-web-plugin/pom.xml
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/agent/web/ResultUtil.java
  apm-agent-plugins/apm-web-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.report.processor.Processor
  apm-agent-plugins/apm-web-plugin/src/main/resources/META-INF/services/org.stagemonitor.configuration.ConfigurationOptionProvider
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  elastic-apm-agent/pom.xml
  elastic-apm-agent/src/test/java/co/elastic/apm/agent/configuration/ConfigurationExporterTest.java
  integration-tests/spring-boot-1-5/src/test/java/co/elastic/apm/spring/boot/SpringBoot1_5IT.java
  integration-tests/spring-boot-2/spring-boot-2-base/src/test/java/co/elastic/apm/spring/boot/AbstractSpringBootTest.java
Labels: [zube]: In Review

#944 Java docs restructure
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/stacktrace/StacktraceConfiguration.java
  docs/configuration.asciidoc
  docs/faq.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/log-correlation.asciidoc
  docs/metrics.asciidoc
  docs/opentracing.asciidoc
  docs/public-api.asciidoc
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  docs/troubleshooting.asciidoc
  docs/tuning-and-overhead.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: Docs

#948 [1.x][docs] Add placeholder changelog.asciidoc
  CHANGELOG.asciidoc
Labels: Docs

#930 Fixes parsing value of trace_methods configuration property
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/methodmatching/configuration/MethodMatcherValueConverter.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/converter/ListValueConverter.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/methodmatching/configuration/MethodMatcherValueConverterTest.java
Labels: [zube]: In Review

#950 ci(jenkins): cancel previous running builds
  Jenkinsfile
Labels: automation
