Repository elastic/apm-agent-java, pull requests merged in 2019-09, with the labels that each got.

#812 improve servlet error capture
  CHANGELOG.md
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ExceptionHandlerInstrumentation.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/AbstractExceptionHandlerInstrumentationTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/ExceptionHandlerInstrumentationWithExceptionHandlerTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/ExceptionHandlerInstrumentationWithExceptionResolverTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/ExceptionHandlerInstrumentationWithGlobalAdviceTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/ExceptionHandlerInstrumentationWithResponseStatusExceptionTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/controller_advice/ControllerAdviceController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/controller_advice/ControllerAdviceRuntimeException.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/controller_advice/GlobalExceptionHandler.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/exception_handler/ExceptionHandlerController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/exception_handler/ExceptionHandlerRuntimeException.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/exception_resolver/ExceptionResolverController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/exception_resolver/ExceptionResolverRuntimeException.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/exception_resolver/RestResponseStatusExceptionResolver.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/response_status_exception/ResponseStatusExceptionController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/exception/testapp/response_status_exception/ResponseStatusRuntimeException.java
  docs/configuration.asciidoc
Labels: [zube]: In Review

#821 Instrument Logger#error(String, Throwable)
  apm-agent-plugins/apm-error-logging-plugin/pom.xml
  apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentation.java
  apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/package-info.java
  apm-agent-plugins/apm-error-logging-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/AbstractErrorLoggingInstrumentationTest.java
  apm-agent-plugins/apm-error-logging-plugin/src/test/java/co/elastic/apm/agent/error/logging/Slf4jLoggingInstrumentationTest.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#831 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/defaults.yml
Labels: [zube]: In Review, automation, ci

#830 Do not throw Exception from remote config poller with empty server_urls
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
Labels: [zube]: In Review

#822 Add Redis Jedis support
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-plugins/apm-redis-plugin/apm-jedis-2-tests/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-jedis-2-tests/src/test/java/co/elastic/apm/agent/redis/jedis/Jedis2InstrumentationTest.java
  apm-agent-plugins/apm-redis-plugin/apm-jedis-3-tests/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-jedis-3-tests/src/test/java/co/elastic/apm/agent/redis/jedis/Jedis3InstrumentationTest.java
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/src/main/java/co/elastic/apm/agent/redis/jedis/JedisInstrumentation.java
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/src/main/java/co/elastic/apm/agent/redis/jedis/JedisSpanNameInstrumentation.java
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/src/main/java/co/elastic/apm/agent/redis/jedis/package-info.java
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-redis-plugin/apm-jedis-plugin/src/test/java/co/elastic/apm/agent/redis/jedis/Jedis1InstrumentationTest.java
  apm-agent-plugins/apm-redis-plugin/apm-redis-common/pom.xml
  apm-agent-plugins/apm-redis-plugin/apm-redis-common/src/main/java/co/elastic/apm/agent/redis/RedisSpanUtils.java
  apm-agent-plugins/apm-redis-plugin/apm-redis-common/src/test/java/co/elastic/apm/agent/redis/AbstractRedisInstrumentationTest.java
  apm-agent-plugins/apm-redis-plugin/pom.xml
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#854 Add top-level log correlation docs page
  apm-agent-core/src/main/java/co/elastic/apm/agent/logging/LoggingConfiguration.java
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/log-correlation.asciidoc
Labels: [zube]: In Review

#801 Add capture_jmx_metrics option
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/MetricRegistry.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/MetricSet.java
  apm-agent-plugins/apm-jmx-plugin/pom.xml
  apm-agent-plugins/apm-jmx-plugin/src/main/java/co/elastic/apm/agent/jmx/JmxConfiguration.java
  apm-agent-plugins/apm-jmx-plugin/src/main/java/co/elastic/apm/agent/jmx/JmxMetric.java
  apm-agent-plugins/apm-jmx-plugin/src/main/java/co/elastic/apm/agent/jmx/JmxMetricTracker.java
  apm-agent-plugins/apm-jmx-plugin/src/main/java/co/elastic/apm/agent/jmx/MapsTokenScanner.java
  apm-agent-plugins/apm-jmx-plugin/src/main/java/co/elastic/apm/agent/jmx/package-info.java
  apm-agent-plugins/apm-jmx-plugin/src/main/resources/META-INF/services/org.stagemonitor.configuration.ConfigurationOptionProvider
  apm-agent-plugins/apm-jmx-plugin/src/test/java/co/elastic/apm/agent/jmx/JmxMetricTrackerTest.java
  apm-agent-plugins/apm-jmx-plugin/src/test/java/co/elastic/apm/agent/jmx/JmxMetricValueConverterTest.java
  apm-agent-plugins/apm-jmx-plugin/src/test/java/co/elastic/apm/agent/jmx/MapsTokenScannerTest.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#823 Issue 819 disconnect apm server client
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/ApmServerConfigurationSource.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerHealthChecker.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/HttpUtils.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
Labels: [zube]: In Progress

#855 Enabling Mule4 Instrumentation
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/RootPackageCustomLocator.java
  apm-agent-plugins/apm-mule4-plugin/pom.xml
  apm-agent-plugins/apm-mule4-plugin/src/main/java/co/elastic/apm/agent/mule4/Mule4OverrideClassLoaderLookupInstrumentation.java
  apm-agent-plugins/apm-mule4-plugin/src/main/java/co/elastic/apm/agent/mule4/package-info.java
  apm-agent-plugins/apm-mule4-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/pom.xml
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#829 Instrument View#render instead of DispatcherServlet#render
  CHANGELOG.md
  apm-agent-plugins/apm-spring-webmvc-plugin/pom.xml
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/DispatcherServletRenderInstrumentation.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/ViewRenderInstrumentation.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/DispatcherServletRenderInstrumentationTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/ViewRenderSubtypeTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/AbstractViewRenderingInstrumentationTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/FreeMarkerViewTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/GroovyTemplateTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/Jackson2JsonViewTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/Jade4jTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/JspViewTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/ThymeleafTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/freemarker/FreeMarkerViewConfiguration.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/freemarker/FreeMarkerViewController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/groovy/GroovyConfiguration.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/groovy/GroovyController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/jackson2json/Jackson2JsonViewConfiguration.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/jackson2json/Jackson2JsonViewController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/jade4j/Jade4jController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/jade4j/Jade4jTemplateConfiguration.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/jsp/JspConfiguration.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/jsp/JspController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/thymeleaf/ThymeleafConfiguration.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/template/thymeleaf/ThymeleafController.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/freemarker/example.ftl
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/groovy/hello.tpl
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/jade/hello.jade
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/jsp/message-view.jsp
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/static/message-view.jsp
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/static/script.js
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/resources/thymeleaf/thymeleaf.html
  docs/configuration.asciidoc
Labels: [zube]: In Progress
