Repository elastic/apm-agent-java, pull requests merged in 2019-04, with the labels that each got.

#553 Use only ascii chars in log statements
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
Labels: [zube]: In Review

#554 Avoid that the reporter blocks server shutdown
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerReporter.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
Labels: [zube]: In Review, type: bug

#560 [APM-CI] docker.io login
  Jenkinsfile
Labels: automation

#558 Adding support for Apache HTTP Async Client
  CHANGELOG.md
  apm-agent-core/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmInstrumentation.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchersTest.java
  apm-agent-plugins/apm-apache-httpclient-plugin/pom.xml
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientHelper.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientHelperImpl.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientInstrumentation.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientRedirectInstrumentation.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/FutureCallbackWrapper.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/HttpAsyncRequestProducerWrapper.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-apache-httpclient-plugin/src/test/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientInstrumentationTest.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ElasticsearchRestClientInstrumentationHelperImpl.java
  apm-agent-plugins/apm-httpclient-core/src/main/java/co/elastic/apm/agent/http/client/HttpClientHelper.java
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#561 [APM-CI] force pull weblogic image from CI
  Jenkinsfile
Labels: [zube]: In Review, automation

#555 Add support for WebLogic
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/ServiceNameUtil.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  docs/setup-javaagent.asciidoc
  docs/supported-technologies.asciidoc
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/WebLogicIT.java
  integration-tests/application-server-integration-tests/src/test/resources/domain.properties
  integration-tests/simple-webapp/src/main/webapp/index.jsp
Labels: [zube]: In Review, state: blocked

#568 [APM-CI] we only need the dockerLogin in the smoke test 2
  Jenkinsfile
Labels: automation

#565 [APM-CI][Java] Add WebLogic container to packer cache
  .ci/packer_cache.sh
Labels: automation

#563 Check if class loader can load class via resource lookup
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
Labels: [zube]: In Review

#562 Allow constructor arguments in service implementations
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmInstrumentation.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ActivationListener.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracerBuilder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/processor/Processor.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/processor/ProcessorEventHandler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/util/DependencyInjectingServiceLoader.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/TestProcessor.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/util/DependencyInjectingServiceLoaderTest.java
  apm-agent-core/src/test/resources/META-INF/services/co.elastic.apm.agent.util.DependencyInjectingServiceLoaderTest$Service
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureTransactionInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientSyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchClientSyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/es/restclient/ElasticsearchRestClientInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jaxws-plugin/src/main/java/co/elastic/apm/agent/jaxws/JaxWsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/PreparedStatementInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/OkHttp3ClientAsyncInstrumentation.java
  apm-agent-plugins/apm-okhttp-plugin/src/main/java/co/elastic/apm/agent/okhttp/OkHttpClientAsyncInstrumentation.java
  apm-agent-plugins/apm-scheduled-annotation-plugin/src/main/java/co/elastic/apm/agent/spring/scheduled/ScheduledTransactionNameInstrumentation.java
  apm-agent-plugins/apm-scheduled-annotation-plugin/src/test/java/co/elastic/apm/agent/spring/scheduled/ScheduledTransactionNameInstrumentationTest.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/FilterChainInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/RequestStreamRecordingInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletInstrumentation.java
  apm-agent-plugins/apm-slf4j-plugin/src/main/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListener.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/ApmHandlerInterceptorTest.java
  apm-agent-plugins/apm-spring-webmvc-plugin/src/test/java/co/elastic/apm/agent/spring/webmvc/DispatcherServletRenderInstrumentationTest.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/agent/web/BodyProcessor.java
  apm-agent-plugins/apm-web-plugin/src/main/java/co/elastic/apm/agent/web/SanitizingWebProcessor.java
  apm-agent-plugins/apm-web-plugin/src/test/java/co/elastic/apm/agent/web/BodyProcessorTest.java
  apm-agent-plugins/apm-web-plugin/src/test/java/co/elastic/apm/agent/web/SanitizingWebProcessorTest.java
  elastic-apm-agent/pom.xml
  elastic-apm-agent/src/test/java/co/elastic/apm/agent/configuration/ConfigurationExporterTest.java
Labels: [zube]: In Review, technical debt

#578 Add thread count metric
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/ThreadMetrics.java
  apm-agent-core/src/main/resources/META-INF/services/co.elastic.apm.agent.context.LifecycleListener
  apm-agent-core/src/test/java/co/elastic/apm/agent/metrics/builtin/ThreadMetricsTest.java
  docs/metrics.asciidoc
Labels: [zube]: In Review

#590 [docs] Clarify javaagent flag
  docs/intro.asciidoc
  docs/setup-javaagent.asciidoc
  docs/setup.asciidoc
Labels: Docs

#591 [docs][1.x] clarify javaagent flag
  docs/intro.asciidoc
  docs/setup-javaagent.asciidoc
  docs/setup.asciidoc
Labels: Docs

#594 Make log_file option work again
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
Labels: [zube]: In Review

#583 Changing Byte Buddy Location Strategy to WEAK
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
Labels: [zube]: In Review

#598 Exclude DumbExecutor
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
Labels: [zube]: In Review

#597 Fix transaction name for non-sampled transactions
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/AbstractSpan.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Transaction.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentationTest.java
Labels: [zube]: In Review

#601 Fix Manifest version reading error to support jar:file protocol
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchersTest.java
Labels: [zube]: In Review, type: bug

#596 Exclude glassfish Executor which does not permit wrapped runnables
  CHANGELOG.md
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/ExcludedExecutorClassTest.java
Labels: [zube]: In Review

#605 Fixing some async mechanisms lifecycle issues
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeBaseWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeCallableWrapper.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/async/SpanInScopeRunnableWrapper.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ScopeManagementTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/ExecutorServiceDoubleWrappingTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/RunnableWrapperExecutorService.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/AsyncInstrumentation.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/helper/ApmAsyncListener.java
Labels: [zube]: In Review

#608 Add note that number and boolean labels require APM Server 6.7+
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#600 Exclude $view proxies from JAX-RS instrumentation
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentationTest.java
Labels: [zube]: In Review

#613 Excluded proxy classes in JaxRs and Executor instrumentation
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java
  apm-agent-plugins/apm-jaxrs-plugin/src/test/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentationTest.java
Labels: [zube]: In Review

#577 Discard fast methods coming from trace_methods
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/methodmatching/TraceMethodInstrumentation.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/methodmatching/MethodMatcherInstrumentationTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/methodmatching/TraceMethodInstrumentationTest.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java
  apm-agent-plugins/apm-java-concurrent-plugin/src/test/java/co/elastic/apm/agent/concurrent/AsyncTraceMethodInstrumentationTest.java
  docs/configuration.asciidoc
Labels: [zube]: In Review, type: enhancement
