Repository elastic/apm-agent-java, pull requests merged in 2019-08, with the labels that each got.

#761 Fix 6.x APM Server version parsing
  CHANGELOG.md
  apm-agent-core/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerHealthChecker.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
Labels: type: bug

#772 Improve HttpClient matching filtering
  CHANGELOG.md
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpAsyncClientInstrumentation.java
  apm-agent-plugins/apm-apache-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/ApacheHttpClientInstrumentation.java
Labels: [zube]: In Review

#733 [docs] Clarify application_packages
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/stacktrace/StacktraceConfiguration.java
  docs/configuration.asciidoc
Labels: Docs, [zube]: In Review

#685 Add hibernate search support
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/src/main/java/co/elastic/apm/agent/hibernate/search/v5_x/HibernateSearch5Instrumentation.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/src/test/java/co/elastic/apm/agent/hibernate/search/v5_x/Dog.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/src/test/java/co/elastic/apm/agent/hibernate/search/v5_x/EntityManagerFactoryHelper.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/src/test/java/co/elastic/apm/agent/hibernate/search/v5_x/HibernateSearch5InstrumentationTest.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-5_x/src/test/resources/META-INF/persistence.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/src/main/java/co/elastic/apm/agent/hibernate/search/v6_x/HibernateSearch6Instrumentation.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/src/test/java/co/elastic/apm/agent/hibernate/search/v6_x/Dog.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/src/test/java/co/elastic/apm/agent/hibernate/search/v6_x/EntityManagerFactoryHelper.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/src/test/java/co/elastic/apm/agent/hibernate/search/v6_x/HibernateSearch6InstrumentationTest.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-6_x/src/test/resources/META-INF/persistence.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-common/pom.xml
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-common/src/main/java/co/elastic/apm/agent/hibernate/search/HibernateSearchConstants.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-common/src/main/java/co/elastic/apm/agent/hibernate/search/HibernateSearchHelper.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-common/src/test/java/co/elastic/apm/agent/hibernate/search/DeleteFileVisitor.java
  apm-agent-plugins/apm-hibernate-search-plugin/apm-hibernate-search-plugin-common/src/test/java/co/elastic/apm/agent/hibernate/search/HibernateSearchAssertionHelper.java
  apm-agent-plugins/apm-hibernate-search-plugin/pom.xml
  apm-agent-plugins/pom.xml
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#785 [docs] Configuration updates
  docs/configuration.asciidoc
Labels: Docs

#771 Support annotation matching for TraceMethodInstrumentation
  CHANGELOG.md
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/methodmatching/MethodMatcher.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/methodmatching/TraceMethodInstrumentation.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/matcher/AnnotationMatcher.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/methodmatching/TraceMethodInstrumentationTest.java
  docs/configuration.asciidoc
  integration-tests/application-server-integration-tests/pom.xml
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/AbstractServletContainerIntegrationTest.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/JBossIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/PayaraIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/TomcatIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/WebLogicIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/WebSphereIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/WildFlyIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/CdiApplicationServerTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/CdiServletContainerTestApp.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/tests/JsfApplicationServerTestApp.java
  integration-tests/cdi-app/cdi-app-dependent/pom.xml
  integration-tests/cdi-app/cdi-app-dependent/src/main/java/co/elastic/apm/test/GreeterManager.java
  integration-tests/cdi-app/cdi-app-dependent/src/main/java/co/elastic/apm/test/GreeterManagerImpl.java
  integration-tests/cdi-app/cdi-app-dependent/src/main/java/co/elastic/apm/test/GreeterServlet.java
  integration-tests/cdi-app/cdi-app-dependent/src/main/webapp/WEB-INF/beans.xml
  integration-tests/cdi-app/cdi-app-dependent/src/main/webapp/WEB-INF/web.xml
  integration-tests/cdi-app/cdi-app-dependent/src/main/webapp/status.html
  integration-tests/cdi-app/cdi-app-standalone/pom.xml
  integration-tests/cdi-app/pom.xml
  integration-tests/pom.xml
Labels: [zube]: In Review

#793 chore: update build status URL
  README.md
Labels: Docs, automation, type: chore

#792 ci(jenkins): MAVEN_CONFIG at the top level and also per group of stages
  Jenkinsfile
Labels: automation, ci, enhancement

#800 Make BlockingQueue API test less flaky
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/api/BlockingQueueContextPropagationTest.java
Labels: [zube]: In Review

#804 Tomcat memory leak - change WeakConcurrentMap's cleaner thread's CCL centrally
  apm-agent-core/src/main/java/co/elastic/apm/agent/util/DataStructures.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelper.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelperImpl.java
  apm-agent-plugins/apm-urlconnection-plugin/src/main/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentation.java
Labels: [zube]: In Review

#806 ci: packer cache script should fail never to help to cache dependencies
  .ci/packer_cache.sh
Labels: automation, type: bug

#810 ci(jenkins): avoid using the any agent to skip running in the master-worker
  Jenkinsfile
Labels: automation, ci, enhancement

#820 Revert "ci(jenkins): avoid using the any agent to skip running in the master-worker (#810)"
  Jenkinsfile
Labels: automation, ci
