Repository elastic/apm-agent-java, pull requests merged in 2020-06, with the labels that each got.

#1205 ignore jps JVM for runtime attach
  apm-agent-attach/src/main/java/co/elastic/apm/attach/JvmDiscoverer.java
  apm-agent-attach/src/main/java/co/elastic/apm/attach/RemoteAttacher.java
  apm-agent-attach/src/test/java/co/elastic/apm/attach/JvmDiscovererTest.java
Labels: [zube]: In Review

#1216 ci: run benchmark on a PR basis if comment
  Jenkinsfile
Labels: automation, ci

#1052 add support for the Apache Dubbo
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/MockReporter.java
  apm-agent-plugins/apm-dubbo-plugin/pom.xml
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/AbstractAlibabaDubboInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/AbstractDubboInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/AlibabaMonitorFilterInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/AlibabaResponseCallbackInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/AlibabaResponseFutureInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/AlibabaRpcContextInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/ApacheMonitorFilterInstrumentation.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/advice/AlibabaMonitorFilterAdvice.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/advice/ApacheMonitorFilterAdvice.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/advice/package-info.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/AlibabaDubboAttachmentHelper.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/AlibabaDubboAttachmentHelperImpl.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/ApacheDubboAttachmentHelper.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/ApacheDubboAttachmentHelperImpl.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/AsyncCallbackCreator.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/AsyncCallbackCreatorImpl.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/DubboTraceHelper.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/helper/package-info.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/java/co/elastic/apm/agent/dubbo/package-info.java
  apm-agent-plugins/apm-dubbo-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/AbstractDubboInstrumentationTest.java
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/AlibabaDubboInstrumentationTest.java
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/ApacheDubboInstrumentationTest.java
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/ExecutorServiceWrapper.java
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/api/DubboTestApi.java
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/api/exception/BizException.java
  apm-agent-plugins/apm-dubbo-plugin/src/test/java/co/elastic/apm/agent/dubbo/api/impl/DubboTestApiImpl.java
  apm-agent-plugins/pom.xml
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review

#1058 Fully-automated release process
  .ci/release/Jenkinsfile
  .gitignore
  Jenkinsfile
  scripts/jenkins/branch_creation.sh
  scripts/jenkins/check_maven.sh
  scripts/jenkins/docs_check.sh
  scripts/jenkins/docs_release_check/Dockerfile
  scripts/jenkins/docs_release_check/README.md
  scripts/jenkins/docs_release_check/check.py
  scripts/jenkins/docs_release_check/conftest.py
  scripts/jenkins/docs_release_check/lib/__init__.py
  scripts/jenkins/docs_release_check/requirements.txt
  scripts/jenkins/docs_release_check/tests/test_check.py
  scripts/jenkins/generate_release_notes_url.sh
  scripts/jenkins/is_major.sh
  scripts/jenkins/maven_artifact_url.sh
  scripts/jenkins/release_env.sh
  scripts/jenkins/update_cloudfoundry.sh
Labels: automation, ci

#1238 fix: check that docker is installed
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, bug, ci

#1048 Add Scala concurrent plugin
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-scala-concurrent-plugin/pom.xml
  apm-agent-plugins/apm-scala-concurrent-plugin/src/main/java/co/elastic/apm/agent/scala/concurrent/FutureInstrumentation.java
  apm-agent-plugins/apm-scala-concurrent-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-scala-concurrent-plugin/src/test/scala/co/elastic/apm/agent/scala/concurrent/FutureInstrumentationSpec.scala
  apm-agent-plugins/pom.xml
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
  pom.xml
Labels: [zube]: In Progress
