Repository elastic/apm-agent-java, pull requests merged in 2020-07, with the labels that each got.

#1266 ci: fix missing env variable
  Jenkinsfile
Labels: automation

#1276 Handle case correctly in RC parsing for docs search
  scripts/jenkins/docs_release_check/lib/__init__.py
Labels: automation, ci

#1287 Restore inlining for JMS Listener wrapping advice
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
Labels: type: bug

#1289 Minor changes to release process pipeline
  .ci/release/Jenkinsfile
  scripts/jenkins/branch_creation.sh
Labels: [zube]: In Review, automation, ci

#1299 Wrap all shell calls in base_dir in Jenkins release job
  .ci/release/Jenkinsfile
Labels: automation, ci

#1308 Fixes for git error in release pipeline
  .ci/release/Jenkinsfile
  scripts/jenkins/tags.sh
Labels: automation

#1318 Fix syntax error in release job
  .ci/release/Jenkinsfile
Labels: automation

#1319 docs: add disable instructions
  docs/troubleshooting.asciidoc
Labels: Docs
