Repository elastic/apm-agent-java, pull requests merged in 2020-02, with the labels that each got.

#1008 Fix JDBC non-supported getUpdateCount
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/StatementNotSupportingUpdateCount.java
Labels: [zube]: In Review

#1023 Move check for cURL
  scripts/jenkins/build_docker.sh
Labels: automation, ci

#1020 Add log correlation for log4j and log4j2
  CHANGELOG.asciidoc
  apm-agent-benchmarks/pom.xml
  apm-agent-plugins/apm-kafka-plugin/apm-kafka-headers-plugin/src/main/java/co/elastic/apm/agent/kafka/helper/ElasticHeaderImpl.java
  apm-agent-plugins/apm-log-correlation-plugin/pom.xml
  apm-agent-plugins/apm-log-correlation-plugin/src/main/java/co/elastic/apm/agent/mdc/MdcActivationListener.java
  apm-agent-plugins/apm-log-correlation-plugin/src/main/java/co/elastic/apm/agent/mdc/package-info.java
  apm-agent-plugins/apm-log-correlation-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.impl.ActivationListener
  apm-agent-plugins/apm-log-correlation-plugin/src/test/java/co/elastic/apm/agent/mdc/MdcActivationListenerTest.java
  apm-agent-plugins/apm-slf4j-plugin/src/main/java/co/elastic/apm/agent/slf4j/Slf4JMdcActivationListener.java
  apm-agent-plugins/apm-slf4j-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.impl.ActivationListener
  apm-agent-plugins/pom.xml
  docs/supported-technologies.asciidoc
  elastic-apm-agent/pom.xml
Labels: [zube]: In Review, type: enhancement

#1017 Small change in main configuration doc
  docs/configuration.asciidoc
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: component: documentation

#1027 [docs] Update 1.13.0 release notes
  CHANGELOG.asciidoc
Labels: Docs

#1028 [docs] Details on documentation release process
  CONTRIBUTING.md
Labels: Docs

#1030 Set correct Docker namespace
  scripts/jenkins/push_docker.sh
Labels: automation, ci

#1015 return error id with captureException in public api
  CHANGELOG.asciidoc
  apm-agent-api/src/main/java/co/elastic/apm/api/AbstractSpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/AbstractSpanInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/plugin/api/TransactionInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Review

#1034 ci(jenkins): avoid duplicated builds and reduce the polling
  .ci/jobs/defaults.yml
Labels: automation, ci

#1022 Rework trace_methods docs
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  docs/configuration.asciidoc
Labels: Docs, [zube]: In Review

#1045 ci(jenkins): run opbeans validation per PR
  Jenkinsfile
Labels: automation

#1059 ci(jenkins): apm-its-downstream params has changed
  Jenkinsfile
Labels: automation
