Repository elastic/apm-agent-java, pull requests merged in 2020-11, with the labels that each got.

#1467 Agent load testing
  .ci/load/Jenkinsfile
  .ci/load/README.md
  .ci/load/scripts/app.sh
  .ci/load/scripts/fetch_sdk.sh
  .ci/load/scripts/load_agent.sh
  .ci/load/scripts/locustfile.py
  .ci/load/scripts/param_gen/gen_params.py
  .ci/load/scripts/start.sh
  .ci/load/scripts/tests/simulate_app_start.sh
  .ci/load/scripts/tests/simulate_register.sh
Labels: automation, ci

#1487 [automation] Correct difference in newline determination
  .ci/load/scripts/fetch_sdk.sh
Labels: automation, ci

#1489 [load-testing] Use standard port on orchestrator
  .ci/load/Jenkinsfile
Labels: automation, ci

#1491 [load-test] Account for no domain set in workers
  .ci/load/scripts/app.sh
Labels: automation, ci

#1493 [load-generation] Remove hard-coded test run time
  .ci/load/scripts/load_agent.sh
Labels: automation, ci

#1449 feature added setLabel methods to Span, Transaction of public api
  CHANGELOG.asciidoc
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopSpan.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopTransaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Span.java
  apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/Transaction.java
  apm-agent-api/src/main/java/co/elastic/apm/api/TransactionImpl.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/pluginapi/SpanInstrumentationTest.java
  apm-agent-plugins/apm-api-plugin/src/test/java/co/elastic/apm/agent/pluginapi/TransactionInstrumentationTest.java
  docs/public-api.asciidoc
Labels: [zube]: In Progress

#1494 [load-generation] Small docs change
  .ci/load/Jenkinsfile
Labels: automation, ci

#1511 Remove special handling for MariaDB
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
Labels: flaky-test

#1514 Added GitHub Actions workflow for auto-labeling
  .github/labeler-config.yml
  .github/workflows/labeler.yml
Labels: agent-java

#1516 [automation] Correct SPID lookup in release job
  .ci/release/Jenkinsfile
Labels: automation, ci

#1517 [load test] Make locust respect user setting
  .ci/load/scripts/load_agent.sh
Labels: automation, ci

#1518 Add JVM params to load testing
  .ci/load/Jenkinsfile
  .ci/load/scripts/param_gen/gen_params.py
  .ci/load/scripts/param_gen/requirements.txt
Labels: agent-java

#1520 [load-testing] Always build agent with Java 11
  .ci/load/Jenkinsfile
Labels: agent-java, automation, ci

#1525 [load test] Use 7.x application when Java 7 is requested
  .ci/load/Jenkinsfile
  .ci/load/scripts/java_major.sh
Labels: agent-java, automation, ci

#1527 bypass TLS download error for old JDKs
  .ci/load/Jenkinsfile
Labels: agent-java

#1405 migrate jsf plugin to indy
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-jsf-plugin/src/main/java/co/elastic/apm/agent/jsf/JsfLifecycleInstrumentation.java
Labels: agent-java

#1526 Fix JSF error in Jetty 9.4 and upgrading Byte Buddy to 1.10.18
  apm-agent-core/pom.xml
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/JettyIT.java
  integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/TomcatIT.java
  integration-tests/jsf-app/jsf-app-standalone/pom.xml
  pom.xml
Labels: agent-java

#1533 Update ecs-logging-java link
  docs/log-correlation.asciidoc
Labels: agent-java

#1486 [dependabot] enable for maven multimodule
  .github/dependabot.yml
Labels: agent-java, automation, type: chore

#1508 remove useless allocation in TraceState.copyOf()
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ConstantSampler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/ProbabilitySampler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/sampling/Sampler.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceState.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/sampling/ProbabilitySamplerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/TraceContextTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/transaction/TraceStateTest.java
Labels: agent-java

#1531 Fix NPE when async ES client is nested within Hibernate search
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/main/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchClientAsyncInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-6_4/src/main/java/co/elastic/apm/agent/es/restclient/v6_4/ElasticsearchClientAsyncInstrumentation.java
Labels: agent-java

#1532 Limit public API accessibility to APIs only
  CHANGELOG.asciidoc
  apm-agent-api/src/main/java/co/elastic/apm/api/AbstractSpanImpl.java
  apm-agent-api/src/main/java/co/elastic/apm/api/NoopScope.java
  apm-agent-api/src/main/java/co/elastic/apm/api/ScopeImpl.java
Labels: agent-java

#1537 Send error.transaction_id and error.parent_id only if there is trace_id
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
Labels: agent-java

#1538 Fix formatting for trace_methods_duration_threshold
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  docs/configuration.asciidoc
Labels: agent-java

#1524 Fix spring resttemplate 3.0 support
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-httpclient-core/src/main/java/co/elastic/apm/agent/http/client/HttpClientHelper.java
  apm-agent-plugins/apm-httpclient-core/src/test/java/co/elastic/apm/agent/httpclient/AbstractHttpClientInstrumentationTest.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/pom.xml
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/main/java/co/elastic/apm/agent/resttemplate/SpringRestRequestHeaderSetter.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/main/java/co/elastic/apm/agent/resttemplate/SpringRestTemplateAdvice.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/main/java/co/elastic/apm/agent/resttemplate/SpringRestTemplateInstrumentation.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/main/java/co/elastic/apm/agent/resttemplate/package-info.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.sdk.ElasticApmInstrumentation
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/test/java/co/elastic/apm/agent/resttemplate/SpringRestTemplateInstrumentationTest.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/test/java/co/elastic/apm/agent/resttemplate/SpringRestTemplateIntegrationNoOp.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-plugin/src/test/java/co/elastic/apm/agent/resttemplate/SprintRestTemplateIntegration.java
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-test/pom.xml
  apm-agent-plugins/apm-spring-resttemplate/apm-spring-resttemplate-test/src/test/java/co/elastic/apm/agent/resttemplate/SpringRestTemplateVersionsIT.java
  apm-agent-plugins/apm-spring-resttemplate/pom.xml
  apm-agent-plugins/pom.xml
  docs/supported-technologies.asciidoc
Labels: agent-java

#1530 [cache][ci] use cached m2 repository
  Jenkinsfile
Labels: agent-java, automation, ci

#1394 migrate to indy jms plugin
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/MessagingConfiguration.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/main/java/co/elastic/apm/agent/jms/BaseJmsInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelper.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelperImpl.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/main/java/co/elastic/apm/agent/jms/JmsMessageConsumerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/main/java/co/elastic/apm/agent/jms/JmsMessageListenerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/main/java/co/elastic/apm/agent/jms/JmsMessageProducerInstrumentation.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/test/java/co/elastic/apm/agent/jms/ActiveMqArtemisFacade.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/test/java/co/elastic/apm/agent/jms/ActiveMqFacade.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/test/java/co/elastic/apm/agent/jms/BrokerFacade.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-plugin-base/src/test/java/co/elastic/apm/agent/jms/JmsInstrumentationIT.java
  apm-agent-plugins/apm-jms-plugin/apm-jms-spring-plugin/src/test/java/co/elastic/apm/agent/jms/spring/SpringJmsTest.java
Labels: agent-java
