Repository elastic/apm-agent-java, pull requests merged in 2020-03, with the labels that each got.

#1067 fix: decrease the verbosity of the packer log
  .ci/packer_cache.sh
Labels: automation, ci

#1044 [docs] Add EOL table
  CHANGELOG.md
  CONTRIBUTING.md
  docs/index.asciidoc
  docs/upgrading.asciidoc
Labels: Docs

#1084 Make continuous profiling the default, rename inferred spans config option
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java
  apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/ProfilingConfiguration.java
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#1083 Add API keys support for backend authentication
  CHANGELOG.asciidoc
  Jenkinsfile
  apm-agent-core/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/ReporterConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/ApmServerClientTest.java
  apm-agent-core/src/test/java/specs/ApiKeysStepsDefinitions.java
  apm-agent-core/src/test/java/specs/RunCucumberTest.java
  apm-agent-core/src/test/resources/specs/api_key.feature
  docs/configuration.asciidoc
  scripts/shared-specs/download_gherkins.sh
Labels: [zube]: In Review

#1081 Test that SQLExceptions are rethrown
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/InstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
Labels: [zube]: In Review

#1098 docs: Add link to agent server compatibility matrix
  docs/intro.asciidoc
Labels: Docs

#1100 ci(jenkins): disable stages for only docs
  Jenkinsfile
Labels: automation

#1105 chore: remove automation to pull gherkin specs
  Jenkinsfile
  apm-agent-core/pom.xml
  scripts/shared-specs/download_gherkins.sh
Labels: automation
