Repository elastic/apm-agent-java, pull requests merged in 2020-08, with the labels that each got.

#1314 Fixes problem with Vault in release automation
  .ci/release/Jenkinsfile
  scripts/jenkins/fetch_nexus_id.sh
Labels: [zube]: In Review, automation, ci

#1326 Fix service name caching based on context path
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletGlobalState.java
  apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java
  apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletTransactionHelperTest.java
Labels: type: bug

#1331 [CI] benchmark script obsoleted
  .ci/run-benchmarks.sh
Labels: automation

#1346 test: synchronizing gherkin spec
  apm-agent-core/src/test/resources/specs/api_key.feature
Labels: automation
