Repository elastic/apm-agent-java, pull requests merged in 2020-09, with the labels that each got.

#1377 [CI] fix peer reset when downloading dependencies
  Jenkinsfile
Labels: automation

#1347 test: synchronizing json spec
  apm-agent-core/src/test/java/co/elastic/apm/agent/matcher/WildcardMatcherTest.java
  apm-agent-core/src/test/java/specs/TestJsonSpec.java
  apm-agent-core/src/test/resources/json-specs/sql_signature_examples.json
  apm-agent-core/src/test/resources/json-specs/sql_token_examples.json
  apm-agent-core/src/test/resources/json-specs/wildcard_matcher_tests.json
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/signature/ScannerTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/signature/SignatureParserTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/resources/signature_tests.json
Labels: automation

#1390 Move SPID check to dir block in release job
  .ci/release/Jenkinsfile
Labels: automation, ci

#1391 Fix HttpUrlConnection instrumentation
  apm-agent-core/src/main/java/co/elastic/apm/agent/bci/classloading/IndyPluginClassLoader.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/bci/InstrumentationTest.java
  apm-agent-plugins/apm-urlconnection-plugin/src/main/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentation.java
Labels: type: bug

#1400 [ci][cache] bump java version
  .ci/packer_cache.sh
Labels: automation

#1399 [CI] Fix reset connection when downloading dependencies
  Jenkinsfile
Labels: automation

#1401 fix: update packer_cache to increase the resilience against network i…
  .ci/packer_cache.sh
Labels: automation, bug, ci

#1414 Avoid serializing the first global label twice
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
Labels: type: bug

#1413 Sanitize metricset tag keys
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java
  apm-agent-plugins/apm-micrometer-plugin/src/main/java/co/elastic/apm/agent/micrometer/MicrometerMeterRegistrySerializer.java
  apm-agent-plugins/apm-micrometer-plugin/src/test/java/co/elastic/apm/agent/micrometer/MicrometerMetricsReporterTest.java
Labels: type: bug

#1418 Relaxing k8s pod discovery pattern some more
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/payload/SystemInfo.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/payload/ContainerInfoTest.java
Labels: type: bug

#1416 Catch HttpUrlConnection Already Connected error
  apm-agent-plugins/apm-urlconnection-plugin/src/main/java/co/elastic/apm/agent/urlconnection/HttpUrlConnectionInstrumentation.java
  apm-agent-plugins/apm-urlconnection-plugin/src/main/java/co/elastic/apm/agent/urlconnection/UrlConnectionPropertyAccessor.java
Labels: bug

#1419 fix micrometer invalid double values
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-micrometer-plugin/src/main/java/co/elastic/apm/agent/micrometer/MicrometerMeterRegistrySerializer.java
  apm-agent-plugins/apm-micrometer-plugin/src/test/java/co/elastic/apm/agent/micrometer/MicrometerMetricsReporterTest.java
Labels: bug
