Repository elastic/apm-agent-java, pull requests merged in 2020-04, with the labels that each got.

#1115 Use span.name='empty query' if db.statement is an empty string
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelperImpl.java
Labels: [zube]: In Review

#1050 Issue 846 add errorid to mdc
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/error/ErrorCapture.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContextHolder.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/logging/LoggingConfiguration.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/report/serialize/DslJsonSerializerTest.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureExceptionInstrumentation.java
  apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/ElasticApmApiInstrumentation.java
  apm-agent-plugins/apm-error-logging-plugin/src/main/java/co/elastic/apm/agent/error/logging/AbstractLoggingInstrumentation.java
  apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-5_6/src/test/java/co/elastic/apm/agent/es/restclient/v5_6/ElasticsearchRestClientInstrumentationIT.java
  apm-agent-plugins/apm-log-correlation-plugin/pom.xml
  apm-agent-plugins/apm-log-correlation-plugin/src/main/java/co/elastic/apm/agent/mdc/MdcActivationListener.java
  apm-agent-plugins/apm-log-correlation-plugin/src/test/java/co/elastic/apm/agent/mdc/MdcActivationListenerIT.java
  apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/ProfilingActivationListener.java
  docs/configuration.asciidoc
  docs/log-correlation.asciidoc
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review

#1137 Don't skip Javadoc when building agent
  Jenkinsfile
Labels: automation

#1124 docs: update config precedence and add dynamic badge
  docs/configuration.asciidoc
  docs/images/dynamic-config.svg
  elastic-apm-agent/src/test/resources/configuration.asciidoc.ftl
Labels: Docs

#1135 docs: How to find slow methods
  docs/images/green-check.svg
  docs/images/red-x.svg
  docs/index.asciidoc
  docs/method-monitoring.asciidoc
  docs/supported-technologies.asciidoc
Labels: Docs

#1139 Avoid side-effects of calling Statement.getUpdateCount
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/StatementInstrumentation.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelper.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelperImpl.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/resources/META-INF/services/co.elastic.apm.agent.bci.ElasticApmInstrumentation
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/AbstractJdbcInstrumentationTest.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/JdbcDbIT.java
  apm-agent-plugins/apm-jdbc-plugin/src/test/resources/testcontainers.properties
Labels: type: bug
