Repository elastic/apm-agent-java, pull requests merged in 2024-01, with the labels that each got.

#3479 Fix NPE in ApacheHttpClientApiAdapter#getHostName
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-apache-httpclient/apm-apache-httpclient-common/src/main/java/co/elastic/apm/agent/httpclient/common/AbstractApacheHttpClientAdvice.java
  apm-agent-plugins/apm-apache-httpclient/apm-apache-httpclient-common/src/main/java/co/elastic/apm/agent/httpclient/common/ApacheHttpClientApiAdapter.java
  apm-agent-plugins/apm-apache-httpclient/apm-apache-httpclient4-plugin/src/main/java/co/elastic/apm/agent/httpclient/v4/helper/ApacheHttpClient4ApiAdapter.java
  apm-agent-plugins/apm-apache-httpclient/apm-apache-httpclient5-plugin/src/main/java/co/elastic/apm/agent/httpclient/v5/ApacheHttpClient5Instrumentation.java
  apm-agent-plugins/apm-apache-httpclient/apm-apache-httpclient5-plugin/src/main/java/co/elastic/apm/agent/httpclient/v5/helper/ApacheHttpClient5ApiAdapter.java
  apm-agent-plugins/apm-apache-httpclient/apm-apache-httpclient5-plugin/src/test/java/co/elastic/apm/agent/httpclient/v5/ApacheHttpClientExecuteOpenInstrumentationTest.java
Labels: agent-java, community, triage

#3483 rollback #3444 bump of jctools from 4.0.2 to 4.0.1 to keep java 7 compatibility
  apm-agent-core/pom.xml
Labels: agent-java

#3474 fix span stacktrace capture
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Span.java
  apm-agent-core/src/test/java/co/elastic/apm/agent/impl/ElasticApmTracerTest.java
Labels: bug, agent-java

#3484 add missing changelog entry for jctools PR
  CHANGELOG.asciidoc
Labels: agent-java

#3475 Add db.statement and user attributes to OpenTelemetry Plugin
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-opentelemetry/apm-opentelemetry-plugin/src/main/java/co/elastic/apm/agent/opentelemetry/tracing/OTelSpan.java
Labels: agent-java, community, triage

#3493 ci(release): use new set of credentials for GPG and Maven Central
  .buildkite/README.md
  .buildkite/hooks/prepare-release.sh
  .ci/release.sh
  .ci/snapshot.sh
Labels: automation, agent-java, Team:Automation

#3504 Add disabled central config as a caveat to lambda docs
  docs/setup-aws-lambda.asciidoc
Labels: agent-java

#3497 updatecli: dynamic specs
  .ci/updatecli.d/update-gherkin-specs.yml
  .ci/updatecli.d/update-json-specs.yml
  .ci/updatecli.d/update-specs.yml
  .ci/updatecli/updatecli.d/update-gherkin-specs.yml
  .ci/updatecli/updatecli.d/update-json-specs.yml
  .ci/updatecli/updatecli.d/update-specs.yml
  .ci/updatecli/values.yml
  .github/workflows/updatecli.yml
Labels: agent-java

#3506 backstage: add tags for the obltmachine/apmmachine and other things
  catalog-info.yaml
Labels: agent-java
