Repository elastic/apm-agent-java, pull requests merged in 2024-04, with the labels that each got.

#3568 Add exclusion list option for calling DatabaseMetaData.getUserName
  CHANGELOG.asciidoc
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcConfiguration.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelper.java
  apm-agent-plugins/apm-jdbc-plugin/src/main/resources/META-INF/services/org.stagemonitor.configuration.ConfigurationOptionProvider
  apm-agent-plugins/apm-jdbc-plugin/src/test/java/co/elastic/apm/agent/jdbc/helper/JdbcGetUserNameExclusionTest.java
Labels: agent-java

#3581 ci(fix): correct release order
  .github/workflows/release.yml
Labels: agent-java

#3591 buildkite: fallback if home is not available
  .buildkite/hooks/prepare-common.sh
Labels: agent-java

#3588 Prevent cycles in inferred spans
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceContext.java
  apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/CallTree.java
  apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/ChildList.java
  apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/SamplingProfiler.java
  apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeSpanifyTest.java
  apm-agent-plugins/apm-profiling-plugin/src/test/java/co/elastic/apm/agent/profiler/CallTreeTest.java
Labels: agent-java

#3595 [ci] add list of published artifacts
  .ci/scripts/published-artifacts-list.sh
Labels: agent-java

#3594 github-actions: enable provenance for the jar files
  .buildkite/release.yml
  .buildkite/snapshot.yml
  .ci/release.sh
  .ci/scripts/published-artifacts-list.sh
  .ci/snapshot.sh
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: agent-java

#3584 [Automation] Update JSON server schema specs
  apm-agent-core/src/test/resources/apm-server-schema/current/metadata.json
Labels: automation, agent-java

#3596 [ci] fix GH release version tag
  .github/workflows/release.yml
Labels: agent-java

#3597 [ci] fix artifact list path
  .ci/published-artifacts-list.sh
Labels: agent-java

#3599 Upgrade JDK compatibility tests
  .github/workflows/main.yml
  apm-agent-core/src/test/java/co/elastic/apm/agent/util/JdkVersionTest.java
Labels: agent-java, ci:jdk-compatibility

#3601 github-action: add attestations scope
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: agent-java

#3598 Universal profiling integration: write shared memory
  apm-agent-common/src/main/java/co/elastic/apm/agent/common/util/AgentInfo.java
  apm-agent-core/pom.xml
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/UniversalProfilingConfiguration.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/metadata/SystemInfo.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/Id.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/universalprofiling/ProfilerSharedMemoryWriter.java
  apm-agent-core/src/main/java/co/elastic/apm/agent/universalprofiling/UniversalProfilingIntegration.java
  apm-agent-core/src/main/resources/META-INF/services/org.stagemonitor.configuration.ConfigurationOptionProvider
  apm-agent-core/src/test/java/co/elastic/apm/agent/universalprofiling/UniversalProfilingIntegrationTest.java
Labels: agent-java, ci:jdk-compatibility, ci:windows

#3606 ci(release): tag AWS with the ver prefix
  .github/workflows/release.yml
Labels: agent-java

#3600 release: use tag version for docker build/push
  .github/workflows/release.yml
  CONTRIBUTING.md
  scripts/docker-release/build_docker.sh
  scripts/docker-release/push_docker.sh
Labels: agent-java
