Repository elastic/apm-agent-java, pull requests merged in 2024-09, with the labels that each got.

#3746 enhance class name detection
  CHANGELOG.asciidoc
  apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParser.java
  apm-agent-plugin-sdk/src/main/java/co/elastic/apm/agent/sdk/bytebuddy/SimpleMethodSignatureOffsetMappingFactory.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/ClassNameParserTest.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/AnonymousClass.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/AnonymousNestedClass.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/Dollar$Class.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/ParentClass.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/ParentObject.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/ScalaObject$.java
  apm-agent-plugin-sdk/src/test/java/co/elastic/apm/agent/sdk/bytebuddy/clazzes/SimpleClass.java
  apm-agent-plugins/apm-scheduled-annotation-plugin/src/test/java/co/elastic/apm/agent/scheduled/TimerTaskInstrumentationTest.java
Labels: agent-java, community, triage

#3785 deps(updatecli): bump all policies
  .ci/updatecli/values.d/apm-data-spec.yml
  .ci/updatecli/values.d/apm-gherkin.yml
  .ci/updatecli/values.d/apm-json-specs.yml
  .ci/updatecli/values.d/scm.yml
  updatecli-compose.yaml
Labels: dependencies, agent-java

#3787 deps(updatecli): bump all policies
  updatecli-compose.yaml
Labels: dependencies, agent-java

#3797 Fix test-reporter workflow
  .github/workflows/test-reporter.yml
Labels: agent-java

#3794 deps(updatecli): bump all policies
  updatecli-compose.yaml
Labels: dependencies, agent-java

#3796 github-action: use oblt-actions/maven/await-artifact
  .github/workflows/release-step-3.yml
Labels: agent-java

#3798 Bump upload- and download-artifact to v4
  .github/workflows/stash/action.yml
  .github/workflows/unstash/action.yml
Labels: agent-java

#3802 Make health metrics GA
  CHANGELOG.asciidoc
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/MetricsConfigurationImpl.java
  docs/configuration.asciidoc
  docs/metrics.asciidoc
Labels: agent-java

#3799 [DOCS] Clarify the frequency of config polling
  apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfigurationImpl.java
  docs/configuration.asciidoc
Labels: agent-java

#3789 github-action: use ephemeral tokens with the required permissions
  .github/workflows/updatecli.yml
Labels: agent-java

#3808 ci: use GitHub app for ephemeral tokens
  .buildkite/hooks/prepare-common.sh
Labels: agent-java

#3801 ci: use GitHub app for ephemeral tokens
  .github/workflows/pre-post-release.yml
  .github/workflows/release-step-3.yml
Labels: agent-java

#3819 github-action: use elastic/oblt-actions/github/is-member-of
  .github/workflows/labeler.yml
Labels: agent-java
